logging:
  level:
    com:
      jooq:
        app: INFO
spring:
  application:
    name: JhipsterSampleApplication
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/jhipsterSampleApplication
    username: jhipsterSampleApplication
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  jackson:
    default-property-inclusion: non_null
jhlite-hidden-resources:
  # Disable the modules and its dependencies by slugs
  slugs: custom-jhlite
server:
  port: 8080
